apiVersion: apps/v1
kind: Deployment
metadata:
  name: segmentation-worker
spec:
  selector:
    matchLabels:
      app: segmentation-worker
  replicas: 2
  template:
    metadata:
      labels:
        app: segmentation-worker
    spec:
      containers:
      - name: segmentation-worker
        image: kaidrumm/segmentation:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 3Gi
          requests:
            cpu: 100m
            memory: 1Gi
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: MINIO_HOST
          value: "minio:9000"
        ports:
        - containerPort: 5003